server:
  port: 8088

spring:
  datasource:
    # 数据库连接URL
    url: jdbc:postgresql://139.9.240.37:5432/workplace_test?charset=utf-8&sslmode=disable
    # 数据库用户名
    username: postgres
    # 数据库密码
    password: korant@123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      # 连接池初始化时创建的连接数
      initialSize: 5
      # 连接池中最大连接数
      maxActive: 50
      # 连接池中最小空闲连接数
      minIdle: 5
      # 连接池中最大空闲连接数(已弃用)
      #maxIdle: 10
      # 获取连接时的最大等待时间（毫秒）
      maxWait: 60000
      # 间隔多久检测一次空闲连接（毫秒）
      timeBetweenEvictionRunsMillis: 60000
      # 连接池中连接最小空闲时间（毫秒）
      minEvictableIdleTimeMillis: 300000
      # 用于检测连接是否有效的SQL语句
      validationQuery: SELECT 1
      # 是否开启空闲连接的检测
      testWhileIdle: true
      # 是否开启连接的检测功能，在获取连接时检测连接是否有效
      testOnBorrow: false
      # 是否开启连接的检测功能，在归还连接时检测连接是否有效
      testOnReturn: false
      # 是否缓存PreparedStatement对象
      poolPreparedStatements: true
      # 缓存PreparedStatement对象的最大数量
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计用的filter，允许监控统计
      filters: stat
      # 配置扩展属性，用于监控统计分析SQL性能等
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  data:
    redis:
      database: 0
      host: 139.9.240.37
      port: 6379
      password: korant@123
      lettuce:
        pool:
          max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 10 # 连接池中的最大空闲连接
          min-idle: 5 # 连接池中的最小空闲连接
          max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      connect-timeout: 300 # 连接超时时间（毫秒）

  rabbitmq:
    addresses: 139.9.240.37:5672
    virtual-host: /
    publisher-confirm-type: correlated # 确认消息已发送到交换机(Exchange)
    publisher-returns: true  # 开启发送端消息抵达队列的确认
    template:
      mandatory: true
    username: korant
    password: korant@12345
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

env_version: trial

enterprise_qrcode_url: https://tweichat.youyai.cn/?qrcodeId=

notify_url: https://tweichat.youyai.cn/workplace/user/rechargeNotify

rabbitmq:
  delayProperties:
    enterprise_qrcode:
      #交换机名称
      exchangeName: enterprise_qrcode_test_exchange
      #队列名称
      queueName: enterprise_qrcode_test_queue
      #路由键
      routingKey: enterprise_qrcode
      #消费者类型
      consumerType: enterpriseQrcode
    enterprise_shareImage:
      #交换机名称
      exchangeName: enterprise_shareImage_test_exchange
      #队列名称
      queueName: enterprise_shareImage_test_queue
      #路由键
      routingKey: enterprise_shareImage
      #消费者类型
      consumerType: enterpriseShareImage
    hunt_job_shareImage:
      #交换机名称
      exchangeName: hunt_job_shareImage_test_exchange
      #队列名称
      queueName: hunt_job_shareImage_test_queue
      #路由键
      routingKey: hunt_job_shareImage
      #消费者类型
      consumerType: huntJobShareImage
    job_shareImage:
      #交换机名称
      exchangeName: job_shareImage_test_exchange
      #队列名称
      queueName: job_shareImage_test_queue
      #路由键
      routingKey: job_shareImage
      #消费者类型
      consumerType: jobShareImage